name: windows port

on:
  push:
  pull_request:
    paths:
      - '.github/workflows/*.yml'
      - 'tools/**'
      - 'py/**'
      - 'extmod/**'
      - 'lib/**'
      - 'ports/unix/**'
      - 'ports/windows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: source tools/ci.sh && ci_windows_setup
    - name: Install SDL for LVGL
      run: |
        wget https://www.libsdl.org/release/SDL2-devel-2.0.12-mingw.tar.gz
        tar xzf SDL2-devel-2.0.12-mingw.tar.gz SDL2-2.0.12/
        cd SDL2-2.0.12/
        mkdir /usr/local/{i686,x86_64}-w64-mingw32
        sudo make cross
    - name: Build
      run: source tools/ci.sh && env CFLAGS_EXTRA="-I/usr/local/i686-w64-mingw32/include" LDFLAGS_EXTRA="-L/usr/local/i686-w64-mingw32/lib" ci_windows_build
