name: Build lv_micropython unix port

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install SDL
      run: sudo apt-get install libsdl2-dev
    - name: Update submodules
      run: git submodule update --init --recursive  
    - name: make
      run: make -j $(nproc) -C ports/unix
    
